name: Build and Deploy Apps
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-nextjs:
    name: Build and push next.js image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: djmeph
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Yarn Cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-cache-

      - name: Install Node Modules
        shell: bash
        run: yarn install

      - name: Build app
        shell: bash
        run: yarn nx run digital-www-pwa:build:production
        env:
          NEXT_PUBLIC_API_BASE_URL: https://api.lakesoffire.org
          SERVICE_WORKER_CACHE_ID: ${{ github.sha }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/digital-www-pwa/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/djmeph/lof-digital-www-2025
          cache-from: type=registry,ref=ghcr.io/djmeph/lof-digital-www-2025:buildcache
          cache-to: type=registry,ref=ghcr.io/djmeph/lof-digital-www-2025:buildcache,mode=max
          provenance: false
